// components/CvHeroArea.vue
<template>
  <div class="hero-area hero">
    <div class="container">
      <div class="hero-body">
        <div class="columns">
          <div class="left-column column has-text-right is-three-fifths-touch">
            <div class="parallelogram-image-container is-hidden-tablet">
              <v-lazy-image
                src="../pics/portrait-1-mobile-2x.jpg"
                src-placeholder="../pics/portrait-1-mobile-placeholder.jpg"
              />
            </div>
            <h1 class="title pt-6">
              <div class="text-shape-limiter is-hidden-mobile" />
              <span class="is-size-1 has-text-right">Hi! I’m Pavel Buramensky</span>
              <p class="is-size-2 pt-4">
                I’m a front-end developer who cares about user experience and tries to make the world a better place
              </p>
            </h1>
            <p class="contacts pt-5">
              <span class="mr-5">
                <a href="mailto:mail@paulbu.com">
                  <span class="icon-text">
                    <span class="icon">
                      <MailIcon />
                    </span>
                    <span>Email</span>
                  </span>
                </a>
              </span>
              <span class="mr-5">
                <a href="https://t.me/bupaev">
                  <span class="icon-text">
                    <span class="icon">
                      <TelegramIcon />
                    </span>
                    <span>Telegram</span>
                  </span>
                </a>
              </span>
              <span>
                <a href="https://www.linkedin.com/in/pavel-buramensky/">
                  <span class="icon-text">
                    <span class="icon">
                      <LinkedinIcon />
                    </span>
                    <span>LinkedIn</span>
                  </span>
                </a>
              </span>
              <span class="is-block-tablet">
                <span class="vertical-align-hack mr-2 is-hidden-mobile">also you can</span>
                <a href="/pavel-buramensky-cv.pdf" target="_blank">
                  <span class="icon-text">
                    <span class="icon">
                      <DownloadIcon />
                    </span>
                    <span>Download my CV</span>
                  </span>
                </a>
              </span>
            </p>
          </div>
          <div class="column is-hidden-mobile">
            <div class="parallelogram-image-container">
              <v-lazy-image
                src="../pics/portrait-1-desktop.jpg"
                src-placeholder="../pics/portrait-1-desktop-placeholder.jpg"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import VLazyImage from 'v-lazy-image/v2/v-lazy-image.es'

import LinkedinIcon from '@/assets/icons/linkedin.svg?inline'
import TelegramIcon from '@/assets/icons/telegram.svg?inline'
import MailIcon from '@/assets/icons/mail.svg?inline'
import DownloadIcon from '@/assets/icons/download.svg?inline'

export default {
  name: 'HeroArea',
  components: { VLazyImage, DownloadIcon, MailIcon, LinkedinIcon, TelegramIcon }
}
</script>

<style lang="scss">
@import "assets/scss/mixins.scss";

.hero-area {
  position: relative;
  overflow: hidden;
  margin-bottom: 3rem;
  font-family: $accent-font;
  z-index: 2;

  &::before {
    content: "";
    position: absolute;
    top: -50%;
    bottom: -50%;
    left: -50%;
    right: -50%;
    background: var(--wave-gradient);
    background-size: 50% 100%;
    animation: gradient 15s linear infinite;
    will-change: background-color;
    transform: rotate(15deg);
  }

  &::after {
    content: "";
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    background: repeating-linear-gradient(105deg, var(--background-color) 0, var(--background-color) 3px, transparent 4px, transparent 13px);
    transition: background 500ms;
  }

  .container {
    z-index: 1;
  }

  @keyframes gradient {
    0% {
      background-position: 0 0;
    }
    100% {
      background-position: 200% 0;
    }
  }

  @include desktop-only {
    .container {
      max-width: 960px;
    }
  }

  .hero-body {
    @include tablet {
      padding-right: 0;
      padding-left: 10px;
    }

    @include touch {
      min-height: 500px;
      padding-top: 0;
      padding-bottom: 0;
    }

    @include mobile {
      margin-bottom: 0;
      padding-bottom: 45px;
      padding-right: 20px;
    }
  }

  .left-column {
    z-index: 1;

    // On less than 1050px Hero Area texts are too close to VerticalMenu
    @media screen and (min-width: $desktop) and (max-width: 1050px) {
      flex-grow: 1.25;
      padding-left: 40px;
    }

    @include mobile {
      // can't just use ".is-full-mobile" cause ".is-three-fifths-touch" has higher priority
      width: 100%;
      display: flex;
      flex-direction: column;
      justify-content: center;
      min-height: 478px;

      .parallelogram-image-container {
        position: absolute;
        left: -196px;
        top: 0;
        height: 600px;
        width: 250px;
        margin-right: 0;
        margin-left: 0;
        z-index: 0;

        img {
          position: absolute;
          top: -28px;
          left: 64%;
          transform: skew(15deg) scale(1);
        }
      }
    }
  }

  a {
    position: relative;

    @include text-hover-effect();
  }

  .icon svg {
    width: 100%;
    height: 100%;
    fill: var(--text-color) !important;
  }

  .title {
    position: relative;
    font-weight: 600;
    font-style: italic;
    z-index: 1;

    @include desktop-only {
      margin-right: -50px;
    }

    @include mobile {
      margin-right: -50px;
      padding-left: 8%;
      // padding-top: 0 !important;
    }

    @include tablet-only {
      margin-right: -50px;
      padding-left: 20px;
    }

    @include mobile {
      margin-right: 0;

      @include text-contour(var(--background-color), 0.05em);
    }
  }

  .contacts {
    font-weight: 600;
    font-size: $size-4;
    font-style: italic;

    & > span {
      display: inline-block;
      padding-bottom: 15px;

      a {
        display: inline-block;
        height: 1.3em;
      }
    }

    @include touch {
      font-size: 1.3rem;
    }

    @include mobile {
      display: flex;
      flex-wrap: wrap;
      justify-content: flex-end;

      & > span {
        margin-right: 0 !important;

        a {
          margin-left: 1em;
        }
      }
    }
  }

  .vertical-align-hack {
    display: inline-block;
    vertical-align: top;
    margin-top: -0.25em;
  }

  .text-shape-limiter {
    float: right;
    width: 120px;
    height: 400px;
    shape-outside: polygon(100% 0%, 100% 100%, 0 100%);
    pointer-events: none;

    @include tablet-only {
      width: 135px;
      height: 450px;
    }
  }

  .parallelogram-image-container {
    position: relative;
    overflow: hidden;
    height: 472px;
    margin-left: -50px;
    margin-right: 32px;
    transform: skew(-15deg);
    // filter: drop-shadow(2px 2px 10px rgba(255, 255, 255, 0.2));

    &::after {
      content: "";
      position: absolute;
      top: 0;
      left: 0;
      height: 100%;
      width: 100%;
      background-color: rgba(#fff, 0.05);
    }

    @include desktop-only {
      margin-right: -200px;
      height: 550px;
      margin-left: auto;
    }

    @include touch {
      height: 500px;
      margin-right: -80px;
      margin-left: auto;
    }

    // has to be placed after touch
    @include tablet-only {
      height: 100%;
    }

    img {
      height: 100%;
      transform: skew(15deg) scale(1.22) translateY(-32px);
      object-fit: cover;

      @include desktop-only {
        transform: skew(15deg) scale(1.3) translateY(-25px);
      }

      @include tablet-only {
        transform: skew(15deg) scale(1.3) translate(-14px, -30px);
      }

      @include mobile {
        transform: skew(15deg) scale(1.3) translate(-24px, -30px);
      }
    }
  }
}

</style>

// next-app/components/cv-hero-area/cv-hero-area.tsx
"use client";

import { useState } from "react";
import Image from "next/image";
import styles from "./cv-hero-area.module.scss";

function LinkedinIcon() {
  return (
    <svg
      version="1.1"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 19.9 19.8"
    >
      <path
        fill="currentColor"
        d="M2,18.6c-0.4,0-0.7-0.3-0.7-0.7v-16c0-0.4,0.3-0.7,0.7-0.7h16c0.4,0,0.7,0.3,0.7,0.7v16c0,0.4-0.3,0.7-0.7,0.7H2z
		 M2.7,17.2h14.6V2.6H2.7V17.2z M13.8,15.1v-4c0-1.1-0.9-2-2-2c-1.1,0-2,0.9-2,2v4H8.3V8.2h1.4v0.8l0.5-0.5C10.8,8,11.4,7.7,12,7.7
		c1.8,0,3.2,1.5,3.2,3.5v4H13.8z M4.8,15.1V8.2h1.4v6.9H4.8z M5.5,6.6c-0.7,0-1.2-0.5-1.2-1.2s0.5-1.2,1.2-1.2s1.2,0.5,1.2,1.2
		S6.2,6.6,5.5,6.6z"
      />
    </svg>
  );
}

function TelegramIcon() {
  return (
    <svg
      version="1.1"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 189.473 189.473"
    >
      <path
        fill="currentColor"
        d="M152.531,179.476c-1.48,0-2.95-0.438-4.211-1.293l-47.641-32.316l-25.552,18.386c-2.004,1.441-4.587,1.804-6.914,0.972
		c-2.324-0.834-4.089-2.759-4.719-5.146l-12.83-48.622L4.821,93.928c-2.886-1.104-4.8-3.865-4.821-6.955
		c-0.021-3.09,1.855-5.877,4.727-7.02l174.312-69.36c0.791-0.336,1.628-0.53,2.472-0.582c0.302-0.018,0.605-0.018,0.906-0.001
		c1.748,0.104,3.465,0.816,4.805,2.13c0.139,0.136,0.271,0.275,0.396,0.42c1.11,1.268,1.72,2.814,1.835,4.389
		c0.028,0.396,0.026,0.797-0.009,1.198c-0.024,0.286-0.065,0.571-0.123,0.854L159.898,173.38c-0.473,2.48-2.161,4.556-4.493,5.523
		C154.48,179.287,153.503,179.476,152.531,179.476z M104.862,130.579l42.437,28.785L170.193,39.24l-82.687,79.566l17.156,11.638
		C104.731,130.487,104.797,130.533,104.862,130.579z M69.535,124.178l5.682,21.53l12.242-8.809l-16.03-10.874
		C70.684,125.521,70.046,124.893,69.535,124.178z M28.136,86.782l31.478,12.035c2.255,0.862,3.957,2.758,4.573,5.092l3.992,15.129
		c0.183-1.745,0.974-3.387,2.259-4.624L149.227,38.6L28.136,86.782z"
      />
    </svg>
  );
}

function MailIcon() {
  return (
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
      <path
        fill="currentColor"
        d="M22 20.007a1 1 0 0 1-.992.993H2.992A.993.993 0 0 1 2 20.007V19h18V7.3l-8 7.2-10-9V4a1 1 0 0 1 1-1h18a1 1 0 0 1 1 1v16.007zM4.434 5L12 11.81 19.566 5H4.434zM0 15h8v2H0v-2zm0-5h5v2H0v-2z"
      />
    </svg>
  );
}

function DownloadIcon() {
  return (
    <svg
      version="1.2"
      baseProfile="tiny"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 32 32"
    >
      <polygon
        fill="currentColor"
        points="19.4,25 20.9,23.5 23.6,25.3 23.6,17.6 26.4,17.6 26.4,25.3 29.1,23.5 30.6,25 25,30.6"
      />
      <path
        fill="currentColor"
        d="M7.8,30.4l-2.2-2.2V3.8l2.2-2.2h11.3l7.2,7.2v6.6h-2.8v-3h-5.8l-2.2-2.2V4.4H8.4v23.2h10v2.8H7.8z M23,9.6L18.4,5v4.6H23z"
      />
    </svg>
  );
}

export function CvHeroArea() {
  const [desktopImageLoaded, setDesktopImageLoaded] = useState(false);
  const [mobileImageLoaded, setMobileImageLoaded] = useState(false);

  return (
    <div className={`${styles.heroArea} hero`}>
      <div className="container">
        <div className="hero-body">
          <div className="columns">
            <div
              className={`${styles.leftColumn} column has-text-right is-three-fifths-touch`}
            >
              <div
                className={`${styles.parallelogramImageContainer} is-hidden-tablet`}
              >
                <Image
                  src="/pics/portrait-1-mobile-2x.jpg"
                  alt="Pavel Buramensky portrait"
                  width={250}
                  height={600}
                  priority
                  className={mobileImageLoaded ? styles.loaded : ""}
                  onLoad={() => setMobileImageLoaded(true)}
                />
              </div>
              <h1 className={`title pt-6 ${styles.title}`}>
                <div
                  className={`${styles.textShapeLimiter} is-hidden-mobile`}
                />
                <span className="is-size-1 has-text-right">
                  Hi! I&apos;m Pavel Buramensky
                </span>
                <p className="is-size-2 pt-4">
                  I&apos;m a front-end developer who cares about user experience
                  and tries to make the world a better place
                </p>
              </h1>
              <p className={`${styles.contacts} pt-5`}>
                <span className="mr-5">
                  <a href="mailto:mail@paulbu.com">
                    <span className="icon-text">
                      <span className={`icon ${styles.icon}`}>
                        <MailIcon />
                      </span>
                      <span>Email</span>
                    </span>
                  </a>
                </span>
                <span className="mr-5">
                  <a
                    href="https://t.me/bupaev"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <span className="icon-text">
                      <span className={`icon ${styles.icon}`}>
                        <TelegramIcon />
                      </span>
                      <span>Telegram</span>
                    </span>
                  </a>
                </span>
                <span>
                  <a
                    href="https://www.linkedin.com/in/pavel-buramensky/"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <span className="icon-text">
                      <span className={`icon ${styles.icon}`}>
                        <LinkedinIcon />
                      </span>
                      <span>LinkedIn</span>
                    </span>
                  </a>
                </span>
                <span className="is-block-tablet">
                  <span
                    className={`${styles.verticalAlignHack} mr-2 is-hidden-mobile`}
                  >
                    also you can
                  </span>
                  <a
                    href="/pavel-buramensky-cv.pdf"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <span className="icon-text">
                      <span className={`icon ${styles.icon}`}>
                        <DownloadIcon />
                      </span>
                      <span>Download my CV</span>
                    </span>
                  </a>
                </span>
              </p>
            </div>
            <div className="column is-hidden-mobile">
              <div className={styles.parallelogramImageContainer}>
                <Image
                  src="/pics/portrait-1-desktop.jpg"
                  alt="Pavel Buramensky portrait"
                  fill
                  sizes="(max-width: 768px) 100vw, 50vw"
                  priority
                  className={desktopImageLoaded ? styles.loaded : ""}
                  onLoad={() => setDesktopImageLoaded(true)}
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
