// components/Education.vue
<template>
  <div class="education container">
    <h2 class="title is-2">
      Education
    </h2>
    <div class="content">
      <h3>Endless professional self-development</h3>
      <p>
        Udemy, Coursera, Skillbox, JavaScript.Ninja, Refactoring.Guru and infinite number of articles, books and Youtube videos
      </p>
      <h3>
        Doctor of Philosophy (postgraduate student), Computer science (unfinished)
      </h3>
      <p>
        Omsk State Technical University, 2013 - 2015.
      </p>
      <h3>Master of Science, Computer science</h3>
      <p>
        Omsk State Technical University, July 2011 - GPA 4.9/5.0
      </p>
      <h3>Bachelor of Science, Computer science</h3>
      <p>
        Omsk State Technical University, July 2009 - GPA 4.6/5.0
      </p>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Education'
}
</script>

// src/components/education/education.tsx
export function Education() {
  return (
    <div className="education container">
      <h2 className="title">Education</h2>
      <div className="content">
        <h3>Endless professional self-development</h3>
        <p>
          Udemy, Coursera, Skillbox, JavaScript.Ninja, Refactoring.Guru and
          infinite number of articles, books and Youtube videos
        </p>
        <h3>
          Doctor of Philosophy (postgraduate student), Computer science
          (unfinished)
        </h3>
        <p>Omsk State Technical University, 2013 - 2015.</p>
        <h3>Master of Science, Computer science</h3>
        <p>Omsk State Technical University, 2009-2011 - GPA 4.9/5.0</p>
        <h3>Bachelor of Science, Computer science</h3>
        <p>Omsk State Technical University, 2005-2009 - GPA 4.6/5.0</p>
      </div>
    </div>
  );
}
