// components/VerticalMenu.vue
<template>
  <nav class="vertical-menu">
    <div
      :style="`transform: translateY(${markerOffset - 5}px); height: ${markerHeight}px`"
      class="visible-area-marker"
    />
    <div ref="menu">
      <div
        v-for="(item, index) in items"
        :key="item.id"
        class="item"
        @click="onMenuItemClick(index)"
      >
        <span class="item-icon">
          <img :src="require(`../assets/icons/${item.icon}`)" draggable="false" />
        </span>
        <span class="item-text">
          {{ item.title }}
        </span>
      </div>
    </div>
  </nav>
</template>

<script>
export default {
  name: 'VerticalMenu',
  data () {
    return {
      items: [
        { title: 'Hello!', id: 'hero-area', icon: 'head-with-glasses.svg' },
        { title: 'Overview', id: 'synopsis', icon: 'venn-diagram.svg' },
        { title: 'Skills', id: 'skills', icon: 'pen-and-wrench.svg' },
        { title: 'Experience', id: 'experience', icon: 'mountain-with-flag.svg' },
        { title: 'Education', id: 'education', icon: 'academic-cap.svg' }
      ],
      menuItemHeight: 0,
      contentSectionsHeightArray: [],
      contentSectionsOffsetArray: [],
      scaleCoefficients: [],
      markerOffset: 0,
      markerHeight: 0
    }
  },

  mounted () {
    this.menuItemHeight = this.$refs.menu.getElementsByClassName('item')[0].clientHeight
    this.contentSectionsHeightArray = this.getSectionsProp('clientHeight')
    this.contentSectionsOffsetArray = this.getSectionsProp('offsetTop')

    // menu pixel per content pixel
    this.scaleCoefficients = this.contentSectionsHeightArray.map((SectionsHeight) => {
      return this.menuItemHeight / SectionsHeight
    })

    this.setAreaMarkerPosition()

    window.addEventListener('scroll', this.setAreaMarkerPosition)
    window.addEventListener('resize', this.setAreaMarkerPosition)
  },

  destroyed () {
    window.removeEventListener('scroll', this.setAreaMarkerPosition)
    window.removeEventListener('resize', this.setAreaMarkerPosition)
  },

  methods: {
    onMenuItemClick (targetIndex) {
      window.scrollTo({
        top: this.contentSectionsOffsetArray[targetIndex],
        left: 0,
        behavior: 'smooth'
      })
    },
    getSectionsProp (propName) {
      const sectionsHTMLCollection = document.getElementsByClassName('anchor-for-navigation')
      return [...sectionsHTMLCollection].map(section => section[propName])
    },
    /**
     * Menu items have equal heights but content sections have different heights.
     * We have to map content sections offsets to menu items offsets
     * to mark the current visible page area correctly
     * @param {number} windowScroll
     * @return {number}
     */
    getRescaledOffset (windowScroll) {
      const sectionIndex = this.contentSectionsOffsetArray.findIndex((offset) => {
        return windowScroll < offset
      })

      const selectedMenuItem = sectionIndex === -1
        ? this.contentSectionsOffsetArray.length
        : Math.max(sectionIndex - 1, 0)

      return selectedMenuItem * this.menuItemHeight +
        (windowScroll - this.contentSectionsOffsetArray[selectedMenuItem]) * this.scaleCoefficients[selectedMenuItem]
    },
    setAreaMarkerPosition () {
      const windowTopScrollY = window.scrollY
      const windowBottomScrollY = windowTopScrollY + window.innerHeight

      this.markerOffset = this.getRescaledOffset(windowTopScrollY)

      // when user reaches end of the page make visible area marker equals size of menu item for better look
      if (windowBottomScrollY === document.body.clientHeight) {
        this.markerHeight = this.menuItemHeight
        return
      }

      this.markerHeight = this.getRescaledOffset(windowBottomScrollY) - this.markerOffset
    }
  }
}
</script>

<style lang="scss">
@import "assets/scss/mixins.scss";
@import "~bulma/sass/utilities/_all.sass";

$menu-open-width: 10em;

@mixin menu-transition {
  @for $i from 1 through 5 {
    &:nth-child(#{$i}) {
      transition: width 0.3s #{$i * 0.1}s ease-in-out;
    }
  }
}

.vertical-menu {
  position: fixed;
  top: 10vh;
  left: 10px;
  font-family: "Dosis", sans-serif;
  font-size: 20px;
  z-index: 2;
  user-select: none;

  .item {
    display: flex;
    height: 4em;
    width: 2em;
    overflow: hidden;
    color: #000;
    font-weight: 400;
    text-decoration: none;
    cursor: pointer;
    will-change: auto;

    @include fullhd {
      width: $menu-open-width;
    }

    @include menu-transition;

    .item-text {
      position: relative;
      color: rgba(0, 0, 0, 0.3);

      &::after {
        content: "";
        position: absolute;
        width: 0;
        height: 1.6em;
        left: -0.2em;
        top: 0;
        background: gold;
        transform: scaleY(1) skew(-15deg);
        transition: width 250ms ease;
        z-index: -1;
      }
    }

    .item-icon {
      margin-right: 0.7em;

      img {
        width: 2em;
        max-width: 2em; // override default styles of bulma
      }
    }

    &:hover {
      .item-text::after {
        width: calc(100% + 0.4em);
      }
    }

    &:active {
      .item-text::after {
        transform: scale(1.1) skew(-15deg);
      }
    }
  }

  &:hover {
    .item {
      width: $menu-open-width;

      .item-text {
        color: #000;
      }
    }
  }

  .visible-area-marker {
    position: absolute;
    left: -4px;
    height: 2em;
    width: 2.4em;
    background-color: rgba(gold, 0.1);
    border-radius: 0.5em;
    border: 2px rgba(gold, 0.8) solid;
    pointer-events: none;
  }
}
</style>

// src/components/vertical-menu/vertical-menu.tsx


import { useState, useEffect, useRef, useCallback } from "react";

import { MENU_ITEMS } from "./navigation-config";
import styles from "./vertical-menu.module.scss";

/**
 * Mobile breakpoint for vertical menu positioning behavior.
 * Menu appears below hero and becomes sticky on scroll for viewports <= this width.
 */
const TOUCH_SCREEN_BREAKPOINT = 768;

export function VerticalMenu() {
  const menuRef = useRef<HTMLDivElement>(null);
  const navRef = useRef<HTMLElement>(null);
  const [mounted, setMounted] = useState(false);
  const [menuItemHeight, setMenuItemHeight] = useState(0);
  const [contentSectionsOffsetArray, setContentSectionsOffsetArray] = useState<
    number[]
  >([]);
  const [scaleCoefficients, setScaleCoefficients] = useState<number[]>([]);
  const [markerOffset, setMarkerOffset] = useState(0);
  const [markerHeight, setMarkerHeight] = useState(0);
  // Use ref for hero height to avoid re-renders during scroll/resize measurements
  const heroHeightRef = useRef<number | undefined>(undefined);

  // Set mounted state after hydration
  useEffect(() => {
    setMounted(true);
  }, []);

  /**
   * Retrieves a property value from all navigation anchor sections.
   * Uses section IDs from menu config instead of class name queries.
   */
  const getSectionsProp = useCallback(
    (propName: "clientHeight" | "offsetTop"): number[] => {
      return MENU_ITEMS.map((item) => {
        const section = document.getElementById(item.id);
        return section ? section[propName] : 0;
      });
    },
    []
  );

  /**
   * Calculates the rescaled offset for the visible area marker.
   * Maps content section positions to corresponding menu item positions.
   *
   * Menu items have equal heights but content sections have different heights.
   * This function converts scroll position in the page to corresponding
   * position within the menu to correctly mark the visible area.
   *
   * @param windowScroll - Current window scroll position (scrollY)
   * @param offsets - Array of section offsetTop positions
   * @param coefficients - Scaling coefficients (menuItemHeight / sectionHeight)
   * @param itemHeight - Height of individual menu items
   * @returns Calculated offset for the marker position in pixels
   */
  const getRescaledOffset = useCallback(
    (
      windowScroll: number,
      offsets: number[],
      coefficients: number[],
      itemHeight: number
    ): number => {
      const sectionIndex = offsets.findIndex((offset) => {
        return windowScroll < offset;
      });

      const selectedMenuItem =
        sectionIndex === -1 ? offsets.length : Math.max(sectionIndex - 1, 0);

      return (
        selectedMenuItem * itemHeight +
        (windowScroll - offsets[selectedMenuItem]) *
        coefficients[selectedMenuItem]
      );
    },
    []
  );

  const setAreaMarkerPosition = useCallback(() => {
    if (
      contentSectionsOffsetArray.length === 0 ||
      scaleCoefficients.length === 0 ||
      menuItemHeight === 0
    ) {
      return;
    }

    const windowTopScrollY = window.scrollY;
    const windowBottomScrollY = windowTopScrollY + window.innerHeight;

    const newMarkerOffset = getRescaledOffset(
      windowTopScrollY,
      contentSectionsOffsetArray,
      scaleCoefficients,
      menuItemHeight
    );
    setMarkerOffset(newMarkerOffset);

    // When user reaches end of the page, make visible area marker equal to menu item size
    if (windowBottomScrollY >= document.body.clientHeight) {
      setMarkerHeight(menuItemHeight);
      return;
    }

    setMarkerHeight(
      getRescaledOffset(
        windowBottomScrollY,
        contentSectionsOffsetArray,
        scaleCoefficients,
        menuItemHeight
      ) - newMarkerOffset
    );
  }, [
    contentSectionsOffsetArray,
    scaleCoefficients,
    menuItemHeight,
    getRescaledOffset,
  ]);

  // Initialize menu item heights and section offsets
  useEffect(() => {
    const initMenu = () => {
      if (!menuRef.current) return;

      const firstItem = menuRef.current.querySelector(`.${styles.item}`);
      if (!firstItem) return;

      const itemHeight = (firstItem as HTMLElement).clientHeight;
      setMenuItemHeight(itemHeight);

      const heights = getSectionsProp("clientHeight");
      const offsets = getSectionsProp("offsetTop");

      setContentSectionsOffsetArray(offsets);

      // Calculate scaling coefficients: menu pixels per content pixel
      const coeffs = heights.map((sectionHeight) => {
        return itemHeight / sectionHeight;
      });
      setScaleCoefficients(coeffs);
    };

    // Small delay to ensure DOM is ready
    const timer = setTimeout(initMenu, 100);

    return () => clearTimeout(timer);
  }, [getSectionsProp]);

  // Handle scroll for marker position updates
  useEffect(() => {
    let ticking = false;

    const handleScroll = () => {
      if (!ticking) {
        requestAnimationFrame(() => {
          setAreaMarkerPosition();
          ticking = false;
        });
        ticking = true;
      }
    };

    // Trigger initial position calculation via scroll handler
    handleScroll();
    window.addEventListener("scroll", handleScroll, { passive: true });
    window.addEventListener("resize", handleScroll);

    return () => {
      window.removeEventListener("scroll", handleScroll);
      window.removeEventListener("resize", handleScroll);
    };
  }, [setAreaMarkerPosition]);

  /**
   * Updates the sticky state based on scroll position.
   * On mobile: menu sticks to top after scrolling past hero area.
   */
  const updateStickyState = useCallback(() => {
    if (!navRef.current || heroHeightRef.current === undefined) return;

    const isScrolledPastHero = window.scrollY >= heroHeightRef.current;
    navRef.current.dataset.sticky = isScrolledPastHero ? "true" : "false";
  }, []);

  // Handle mobile sticky positioning and hero height measurement
  useEffect(() => {
    const updateHeroHeight = () => {
      // Measure the DOM element to determine hero height
      const heroSection = document.getElementById("hero-area");
      if (heroSection) {
        const height = heroSection.clientHeight;
        heroHeightRef.current = height;
        if (navRef.current) {
          navRef.current.style.setProperty("--hero-height", `${height}px`);
        }
      }
    };

    const onResize = () => {
      updateHeroHeight();

      if (window.innerWidth <= TOUCH_SCREEN_BREAKPOINT) {
        updateStickyState();
        window.addEventListener("scroll", updateStickyState, { passive: true });
      } else {
        window.removeEventListener("scroll", updateStickyState);
        if (navRef.current) {
          navRef.current.dataset.sticky = "";
        }
      }
    };

    // Initial setup
    updateHeroHeight(); // Measure immediately
    onResize();
    window.addEventListener("resize", onResize);

    return () => {
      window.removeEventListener("scroll", updateStickyState);
      window.removeEventListener("resize", onResize);
    };
  }, [updateStickyState]);

  const onMenuItemClick = (targetIndex: number) => {
    if (contentSectionsOffsetArray[targetIndex] !== undefined) {
      window.scrollTo({
        top: contentSectionsOffsetArray[targetIndex],
        left: 0,
        behavior: "smooth",
      });
    }
  };


  return (
    <nav
      ref={navRef}
      className={styles.verticalMenu}
      aria-label="Page navigation"
      style={{ opacity: mounted ? 1 : undefined }}
    >
      <div
        className={styles.visibleAreaMarker}
        style={{
          transform: `translateY(${markerOffset}px)`,
          height: `${markerHeight}px`,
        }}
        aria-hidden="true"
      />
      <div ref={menuRef}>
        {MENU_ITEMS.map((item, index) => (
          <button
            key={item.id}
            type="button"
            className={styles.item}
            onClick={() => onMenuItemClick(index)}
            aria-label={`Navigate to ${item.title} section`}
          >
            <span className={styles.itemIcon}>
              <img
                src={item.icon}
                alt=""
                width={32}
                height={32}
                draggable={false}
                aria-hidden="true"
              />
            </span>
            <span className={styles.itemText}>{item.title}</span>
          </button>
        ))}
      </div>
    </nav>

  );
}
